refactor: Renamed Snake_case class to CamelCase
Bulkmailer/BulkMailer-Backend pull request #19
Opened 2023-10-06 18:10 UTC by devaprog

This PR Fixes Naming of all the classes from Snake case to Camel Case

Issue: #3

2023-10-07 08:32 UTC, lakshay-saini-au8 requested changes
Some URL paths are also changed

2023-10-07 08:33 UTC, ClawedCatalyst approved these changes

2023-10-07 08:33 UTC, merged

2023-10-07 08:38 UTC, lakshay-saini-au8 commented
@ClawedCatalyst Hey did you checked that some url Paths are also changed

2023-10-07 09:50 UTC, devaprog commented
Sorry, I forgot to mention: Work in process

2023-10-07 09:55 UTC, devaprog commented on authentication/urls.py
> +    path("UpdateAppPassword/", UpdateAppPassword.as_view()),
Thanks, I got it.

2023-10-08 07:55 UTC, devaprog commented
@ClawedCatalyst also could you add `hactoberfest-accepted` label